import { X } from 'lucide-react';
import CameraScanner from '../scanner/CameraScanner';

function extractReceiptNumber(decodedText) {
  const rawValue = String(decodedText || '').trim();

  if (!rawValue) {
    return '';
  }

  /*
   * Handles the QR value generated by the POS receipt:
   *
   * {
   *   "receiptNumber": "ES-MAIN-20260905-000004",
   *   "saleId": "...",
   *   "totalAmount": 64
   * }
   */
  if (rawValue.startsWith('{')) {
    try {
      const parsedValue = JSON.parse(rawValue);

      if (parsedValue?.receiptNumber) {
        return String(parsedValue.receiptNumber)
          .trim()
          .toUpperCase();
      }
    } catch {
      // Treat invalid JSON as a normal receipt-number string below.
    }
  }

  /*
   * Supports a QR containing only:
   * ES-MAIN-20260905-000004
   */
  return rawValue.toUpperCase();
}

export default function ReceiptScannerModal({
  onClose,
  onReceiptDetected
}) {
  async function handleDetected(decodedText) {
    const receiptNumber = extractReceiptNumber(decodedText);

    if (!receiptNumber) {
      return;
    }

    await onReceiptDetected(receiptNumber);
  }

  return (
    <div className="modal-backdrop">
      <div
        className="modal-card"
        style={{ maxWidth: 640 }}
      >
        <div className="modal-header">
          <div>
            <p className="eyebrow">RECEIPT LOOKUP</p>
            <h3>Scan receipt QR code</h3>
          </div>

          <button
            type="button"
            className="icon-btn"
            onClick={onClose}
            aria-label="Close receipt scanner"
          >
            <X size={20} />
          </button>
        </div>

        <p
          style={{
            marginTop: 0,
            marginBottom: 16,
            color: '#64748b',
            fontSize: 14
          }}
        >
          Point the camera at the QR code printed on the customer receipt.
          The sale will open automatically after a successful scan.
        </p>

        <CameraScanner
          onDetected={handleDetected}
        />

        <div className="modal-actions">
          <button
            type="button"
            className="secondary-btn"
            onClick={onClose}
          >
            Cancel
          </button>
        </div>
      </div>
    </div>
  );
}