import { useState } from 'react';
import { Bell, Database, Globe2, LockKeyhole, Save, ShieldCheck } from 'lucide-react';
import GlassCard from '../components/common/GlassCard';

export default function SettingsPage() {
  const [saved, setSaved] = useState(false); const [settings, setSettings] = useState({ supermarketName: 'EssentialSupermarket', defaultBranch: 'Main Branch', timezone: 'Asia/Manila', lowStockNotifications: true, criticalNotifications: true, sessionDuration: '1d' });
  function change(key, value) { setSettings(current => ({ ...current, [key]: value })); setSaved(false); }
  function save(event) { event.preventDefault(); localStorage.setItem('essential_settings', JSON.stringify(settings)); setSaved(true); }
  return <div><div className="page-heading"><div><p className="eyebrow">SYSTEM CONFIGURATION</p><h1>Settings</h1><p>Configure inventory monitoring preferences for this installation.</p></div></div>{saved && <div className="success-message">Settings saved locally. Connect these fields to a server settings endpoint for multi-device persistence.</div>}<form onSubmit={save} className="settings-grid"><GlassCard className="settings-card"><div className="settings-heading"><Globe2 size={19} /><div><h3>General settings</h3><p>Basic supermarket configuration.</p></div></div><label>System name<input value={settings.supermarketName} onChange={e => change('supermarketName', e.target.value)} /></label><label>Default branch / warehouse<input value={settings.defaultBranch} onChange={e => change('defaultBranch', e.target.value)} /></label><label>Timezone<select value={settings.timezone} onChange={e => change('timezone', e.target.value)}><option value="Asia/Manila">Asia/Manila</option><option value="UTC">UTC</option></select></label></GlassCard><GlassCard className="settings-card"><div className="settings-heading"><Bell size={19} /><div><h3>Alert preferences</h3><p>Control inventory notification behavior.</p></div></div><label className="switch-row"><span><strong>Low-stock notifications</strong><small>Notify accounts when stock reaches reorder level.</small></span><input type="checkbox" checked={settings.lowStockNotifications} onChange={e => change('lowStockNotifications', e.target.checked)} /></label><label className="switch-row"><span><strong>Critical notifications</strong><small>Notify accounts when a product reaches zero.</small></span><input type="checkbox" checked={settings.criticalNotifications} onChange={e => change('criticalNotifications', e.target.checked)} /></label></GlassCard><GlassCard className="settings-card"><div className="settings-heading"><ShieldCheck size={19} /><div><h3>Security</h3><p>Authentication and data protection information.</p></div></div><div className="settings-info"><LockKeyhole size={17} /><span>JWT authentication is enabled for API access.</span></div><div className="settings-info"><Database size={17} /><span>Inventory data is stored in MongoDB.</span></div><label>Session duration<select value={settings.sessionDuration} onChange={e => change('sessionDuration', e.target.value)}><option value="1d">1 day</option><option value="7d">7 days</option><option value="30d">30 days</option></select></label></GlassCard><div className="settings-actions"><button className="primary-btn"><Save size={16} /> Save settings</button></div></form></div>;
}